# hosts.ini

[master]
master_node ansible_host=3.239.192.96

[workers]
worker_1 ansible_host=18.232.145.19
worker_2 ansible_host=44.193.198.195

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/gitops_aws_key
